### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by LaurentRDC**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by LaurentRDC** [comment]
@conda-forge-admin Can somebody with Linux experience help me diagnose what has been tripping this package? The problem is summarized as:

> pandoc-plot: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

**Comment by frcl** [comment]
> pandoc-plot: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

It seems that the `gmp` package was not installed as a dependency, but is required. I think this a dependeny of the haskell runtime, all the haskell packages on my system depend on it.

I think either `conda install gmp` or apt-get install libgmp10` will fix it, but it should be added as a dependency.

Where do you define the dependencies for the conda package?

**Comment by LaurentRDC** [comment]
@conda-forge-admin please rerender

**Comment by LaurentRDC** [comment]
Apparently, it is not as simple as installing `gmp`.

@beckermr, I'm sorry to bother you, but would you be able to help here? It appears that the executable cannot find `libgmp.so.10`.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
Let's try this. Might not be the issue.

**Comment by beckermr** [comment]
Ahhhh. conda-build cannot set the rpath on the binary. You'll need to build the binary in conda-build or figure out a way to set it yourself. I am getting out of my depth here. maybe someone from @conda-forge/core can help?

**Comment by scopatz** [comment]
Yeah, you might need to build it on linux

**Comment by jjhelmus** [comment]
`pandoc-plot` is reported as a statically linked ELF file. Is pandoc-plot using `dlopen` to access libgmp?

**Comment by LaurentRDC** [comment]
> Yeah, you might need to build it on linux

The executable is built on linux (azure-pipelines instance).

> `pandoc-plot` is reported as a statically linked ELF file. Is pandoc-plot using `dlopen` to access libgmp?

It's a binary created using the Glasgow Haskell Compiler. `libgmp` is used internally by GHC, and so I cannot say if GMP is used via something like `dlopen`. 

pandoc-plot itself is not using GMP directly, and so it should be as easy as e.g. [pandoc-crossref](https://github.com/conda-forge/pandoc-crossref-feedstock) or [pandoc](https://github.com/conda-forge/pandoc) to support.

**Comment by LaurentRDC** [comment]
> Ahhhh. conda-build cannot set the rpath on the binary. You'll need to build the binary in conda-build or figure out a way to set it yourself. I am getting out of my depth here. maybe someone from @conda-forge/core can help?

I could try to build it from source, e.g. [like is being done for pandoc](https://github.com/conda-forge/pandoc-feedstock/pull/70/files)

**Comment by beckermr** [comment]
Building from source is what we mean when we say "built" here. Simply copying the executable into the proper path is binary repackaging in conda build terms.

**Comment by LaurentRDC** [comment]
Ok, I will try this shortly

**Comment by LaurentRDC** [comment]
It's not looking good. There are no recent-enough Haskell compiler versions for the OS that is referred to as 'linux' in the recipe. Is that RHEL?

Is it possible to run conda-forge builds on another linux distro?

**Comment by beckermr** [comment]
We just today merged support for centos 7. It will take sometime to iron out the bugs and test things but that is no longer a blocker at least.

**Comment by LaurentRDC** [comment]
How convenient :) Given that this issue should be fixed by building from source (#20), we can close this. Thanks to everyone involved!

**Pull request closed without merging**
